RA-04 Создан фрагмент CategoriesListFragment
Untamos25/RecipesApp pull request #2
Opened 2024-12-02 19:33 UTC by Untamos25

2024-12-02 21:11 UTC, Churickoid requested changes

2024-12-02 21:11 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +        fragmentTransaction.add(R.id.mainContainer, CategoriesListFragment()).commit()
Ты используешь Java метод add из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию `add<>()` из класса FragmentTransaction.kt. 

Именно для импорта метода add нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

И предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-12-02 21:11 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +
Поскольку жизненный цикл фрагмента длиннее, чем у view внутри него, рекомендуется очищать binding в методе onDestroyView.
Подробнее можно почитать здесь: https://developer.android.com/topic/libraries/view-binding#fragments

2024-12-02 21:11 UTC, Churickoid commented on app/src/main/res/values/dimens.xml
> +    <dimen name="corner_radius">8dp</dimen>
Сейчас дублируется ресурс с 8dp дважды, здесь и в magrin_half.
Я в прошлом пр писал, про исправление
![image](https://github.com/user-attachments/assets/6a6ec3f1-dc30-4b49-abac-19d5dfbb2697)

2024-12-03 11:31 UTC, Untamos25 commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +        fragmentTransaction.add(R.id.mainContainer, CategoriesListFragment()).commit()
Материал даётся пока вообще не просто, но с твоими указаниями на ошибки, вроде, начинаю понимать, как это работает, спасибо)

2024-12-03 11:37 UTC, Untamos25 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="corner_radius">8dp</dimen>
Да, после предыдущего твоего комментария я объединил corner_radius с margin_half, но потом подумал, а что если (чисто теоретически) дизайн будет изменён и у кнопок будет другой радиус скругления? Тогда не получится независимо их изменить. И вернул это значение обратно) В общем, сейчас я объединил значения, повторы убрал. Поэтому хочу узнать твоё мнение, как тогда быть в такой ситуации? Добавлять в dimens и style новые отдельные значения скругления, а пока такой необходимости нет, оставлять максимально общие названия?

2024-12-03 15:47 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-12-04 14:56 UTC, merged